name: jelles-workspace-nodejs-jelle-dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: jelles-workspace-nodejs-jelle-dev
    steps:
      - uses: actions/checkout@v4

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.aks_container_registry_host }}
          username: ${{ secrets.aks_container_registry_username }}
          password: ${{ secrets.aks_container_registry_password }}

      # 🔧 Build & push backend (Node.js)
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: githubconnector.azurecr.io/nodejs-jelle-backend:${{ github.sha }}

      # 🔧 Build & push frontend (Angular)
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: githubconnector.azurecr.io/nodejs-jelle-frontend:${{ github.sha }}

      - name: Deploy to AKS
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "$KUBECONFIG_CONTENT" > kubeconfig
          
          for file in k8s/*.yml; do
            echo "Applying $file with IMAGE_TAG=$IMAGE_TAG"
            envsubst < "$file" | kubectl --kubeconfig ./kubeconfig -n jelles-workspace-nodejs-jelle-dev apply -f -
          done
